framework:
    notifier:
        chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo

            # Use SMS, Slack and email for urgent notifications
            urgent: ['sms', 'chat/telegram', 'email']

            # Use Slack for highly important notifications
            high: ['chat/slack']

            # Use browser for medium and low notifications
            medium: ['browser']

        admin_recipients:
            - { email: admin@example.com }

